services:
  db:
    image: postgres:14
    restart: always
    env_file: env.dbcredentials
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  server:
    build: .
    depends_on:
      - db
    ports:
      - "50051:50051"
    env_file: env

volumes:
  db_data: